apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy

spec:
  selector:
    matchLabels:
      app: nginx-k8s
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: nginx-k8s
    spec:
      containers:
      - name: nginx
        image: sherwan123/sherwan123-nginx:{{Build_Number}}
        resources:
          requests:
             memory: 512Mi
             cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: new-nginx-svc


spec:
  selector:
    app: nginx-k8s
  ports:
    - name: http
      port: 80
 

  type: ClusterIP
